repos:
  - repo: local
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
        stages: [pre-commit]
        language: system
        entry: python -m pre_commit_hooks.trailing_whitespace_fixer
        types: [text]

      - id: end-of-file-fixer
        name: end-of-file-fixer
        stages: [pre-commit]
        language: system
        entry: python -m pre_commit_hooks.end_of_file_fixer
        types: [text]

      - id: check-yaml
        name: check-yaml
        stages: [pre-commit]
        language: system
        entry: python -m pre_commit_hooks.check_yaml
        types: [yaml]

      - id: check-added-large-files
        name: check-added-large-files
        stages: [pre-commit]
        language: system
        entry: python -m pre_commit_hooks.check_added_large_files

      - id: check-merge-conflict
        name: check-merge-conflict
        stages: [pre-commit]
        language: system
        entry: python -m pre_commit_hooks.check_merge_conflict
        types: [text]

      - id: detect-private-key
        name: detect-private-key
        stages: [pre-commit]
        language: system
        entry: python -m pre_commit_hooks.detect_private_key
        types: [text]

      - id: check-toml
        name: check-toml
        stages: [pre-commit]
        language: system
        entry: python -m pre_commit_hooks.check_toml
        types: [toml]

  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [pre-commit]
        language: system
        entry: python -m isort
        types: [python]
        args: ["--profile", "black"]

  - repo: local
    hooks:
      - id: black
        name: black
        stages: [pre-commit]
        language: system
        entry: python -m black
        types: [python]

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        stages: [pre-commit]
        language: system
        entry: python -m flake8
        types: [python]
        args: ["--max-line-length=88", "--extend-ignore=E203,W503"]
        exclude: 'env/.*|setup.py'

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        stages: [pre-commit]
        language: system
        entry: python -m mypy
        types: [python]
        args: ["--ignore-missing-imports"]
